/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChestIndexRouteImport } from './routes/chest/index'
import { Route as ChestChestIdIndexRouteImport } from './routes/chest/$chestId/index'

const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestIndexRoute = ChestIndexRouteImport.update({
  id: '/chest/',
  path: '/chest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestChestIdIndexRoute = ChestChestIdIndexRouteImport.update({
  id: '/chest/$chestId/',
  path: '/chest/$chestId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/anotherPage': typeof AnotherPageRoute
  '/chest': typeof ChestIndexRoute
  '/chest/$chestId': typeof ChestChestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/anotherPage': typeof AnotherPageRoute
  '/chest': typeof ChestIndexRoute
  '/chest/$chestId': typeof ChestChestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/anotherPage': typeof AnotherPageRoute
  '/chest/': typeof ChestIndexRoute
  '/chest/$chestId/': typeof ChestChestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/anotherPage'
    | '/chest'
    | '/chest/$chestId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accept-invite' | '/anotherPage' | '/chest' | '/chest/$chestId'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/anotherPage'
    | '/chest/'
    | '/chest/$chestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AnotherPageRoute: typeof AnotherPageRoute
  ChestIndexRoute: typeof ChestIndexRoute
  ChestChestIdIndexRoute: typeof ChestChestIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chest/': {
      id: '/chest/'
      path: '/chest'
      fullPath: '/chest'
      preLoaderRoute: typeof ChestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chest/$chestId/': {
      id: '/chest/$chestId/'
      path: '/chest/$chestId'
      fullPath: '/chest/$chestId'
      preLoaderRoute: typeof ChestChestIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AnotherPageRoute: AnotherPageRoute,
  ChestIndexRoute: ChestIndexRoute,
  ChestChestIdIndexRoute: ChestChestIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
